name: Check Base Image

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Base Image Checker
        id: checkbaseimage
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: "library/alpine:latest"
          image: "dontobi/nextcloud-client.rpi:latest"

      - if: steps.checkbaseimage.outputs.needs-updating == 'true'
        name: Trigger build
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Build Container (Stable)
          repo: dontobi/nextcloud-client.rpi
          token: ${{ secrets.ACTIONS_PAT }}
